<?php
/**
 * Stripe + Supabase secrets for Hostinger PHP API.
 * Generated by `npm run build` / prepare-hostinger — do not commit real keys.
 * Direct browser access is blocked.
 */
if (basename($_SERVER['SCRIPT_FILENAME'] ?? '') === 'stripe-config.php') {
  http_response_code(403);
  header('Content-Type: application/json');
  echo json_encode(['error' => 'Forbidden']);
  exit;
}

return [
  'stripe_secret_key' => getenv('STRIPE_SECRET_KEY') ?: '',
  'supabase_url' => getenv('VITE_SUPABASE_URL') ?: getenv('SUPABASE_URL') ?: '',
  'supabase_service_role_key' => getenv('SUPABASE_SERVICE_ROLE_KEY') ?: '',
  'fee_amount' => (int) (getenv('REGISTRATION_FEE_AMOUNT') ?: getenv('VITE_REGISTRATION_FEE_AMOUNT') ?: '1000'),
  'fee_currency' => strtolower(getenv('REGISTRATION_FEE_CURRENCY') ?: getenv('VITE_REGISTRATION_FEE_CURRENCY') ?: 'usd'),
];
